
import static java.lang.System.exit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
//import static java.time.Clock.system;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Messie
 */
public class formulaire extends javax.swing.JFrame {
    
    ConnectDB connect = new ConnectDB();
    ResultSet rs;
    Statement st;
    

    /**
     * Creates new form formulaire
     */
    public formulaire() {
        initComponents();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtpr = new javax.swing.JTextField();
        combfil = new javax.swing.JComboBox<>();
        combniv = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnaj = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btnquit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jLabel1.setText("ID");

        jLabel2.setText("NOM");

        jLabel3.setText("PRENOM");

        jLabel4.setText("FILIERE");

        jLabel5.setText("NIVEAU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1))
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(100, 60, 89, 219);

        jPanel2.setLayout(null);

        txtid.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtid);
        txtid.setBounds(0, 0, 190, 30);

        txtnom.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtnom);
        txtnom.setBounds(0, 40, 190, 30);

        txtpr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.add(txtpr);
        txtpr.setBounds(0, 80, 190, 30);

        combfil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        combfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir", "Electronique", "Génie Informatique", "Telecommunication", "Génie Industriel" }));
        jPanel2.add(combfil);
        combfil.setBounds(0, 120, 190, 30);

        combniv.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        combniv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choisir", "Licence 1", "Licence 2", "Licence 3", "Master 1", "Master 2" }));
        jPanel2.add(combniv);
        combniv.setBounds(0, 160, 190, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 80, 200, 200);

        jPanel3.setLayout(null);

        btnaj.setText("ajouter");
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });
        jPanel3.add(btnaj);
        btnaj.setBounds(50, 20, 82, 31);

        btnmod.setText("modifier");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });
        jPanel3.add(btnmod);
        btnmod.setBounds(180, 20, 96, 31);

        btnquit.setText("quiter");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });
        jPanel3.add(btnquit);
        btnquit.setBounds(120, 70, 90, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(110, 300, 320, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmodActionPerformed
/**
 * insertion des données dans la base de données
 * @param evt 
 */
    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed
        // TODO add your handling code here:
        
        String id = txtid.getText();
        String nom = txtnom.getText();
        String prenom = txtpr.getText();
        String filiere = combfil.getSelectedItem().toString();
        String niveau = combniv.getSelectedItem().toString();
        String req="INSERT INTO etudiant(nom,prenom,filiere,niveau)VALUES('"+nom+"','"+prenom+"','"+filiere+"','"+niveau+"')";
        try{
            st = connect.resultatConnexion().createStatement();
            st.execute(req);
            JOptionPane.showMessageDialog(null,"requete exécutée ! ");
           
        }catch(SQLException ex){
        System.err.println(ex);
        JOptionPane.showMessageDialog(null, "il ya un problème lors de l'insertion");
        }
        txtid.setText("");
        txtnom.setText("");
        txtpr.setText("");
        combniv.setSelectedItem("choisir");
        combfil.setSelectedItem("choisir");
        
    }//GEN-LAST:event_btnajActionPerformed
/**
 * pour quiter le formulaire, nous devons plus revoir le formulaire apres 
 * chaque enregistrement.
 * @param evt 
 */
    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        // TODO add your handling code here:
       // exit(0);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulaire().setVisible(false);
            }
        });
    }//GEN-LAST:event_btnquitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnquit;
    private javax.swing.JComboBox<String> combfil;
    private javax.swing.JComboBox<String> combniv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpr;
    // End of variables declaration//GEN-END:variables
}
